Repository mojohaus/license-maven-plugin, pull requests merged in 2023-07, with the labels that each got.

#500 Fix #498 add-third-party should not override third-party file with the same content
  src/it/add-third-party-skip-second-execution/invoker.properties
  src/it/add-third-party-skip-second-execution/pom.xml
  src/it/add-third-party-skip-second-execution/postbuild.groovy
  src/it/aggregate-add-third-party-second-execution/child1/pom.xml
  src/it/aggregate-add-third-party-second-execution/invoker.properties
  src/it/aggregate-add-third-party-second-execution/pom.xml
  src/it/aggregate-add-third-party-second-execution/postbuild.groovy
  src/main/java/org/codehaus/mojo/license/AbstractAddThirdPartyMojo.java
  src/main/java/org/codehaus/mojo/license/AbstractLicenseMojo.java
  src/main/java/org/codehaus/mojo/license/AddThirdPartyMojo.java
  src/main/java/org/codehaus/mojo/license/AggregatorAddThirdPartyMojo.java
Labels: bug

#501 Switch components to JSR-330, Require JDK 1.8
  pom.xml
  src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyTool.java
  src/main/java/org/codehaus/mojo/license/api/DependenciesTool.java
  src/main/java/org/codehaus/mojo/license/download/LicensedArtifactResolver.java
  src/main/java/org/codehaus/mojo/license/header/transformer/AptFileHeaderTransformer.java
  src/main/java/org/codehaus/mojo/license/header/transformer/FreeMarkerFileHeaderTransformer.java
  src/main/java/org/codehaus/mojo/license/header/transformer/HtmlFileHeaderTransformer.java
  src/main/java/org/codehaus/mojo/license/header/transformer/JavaFileHeaderTransformer.java
  src/main/java/org/codehaus/mojo/license/header/transformer/JspFileHeaderTransformer.java
  src/main/java/org/codehaus/mojo/license/header/transformer/MySqlFileHeaderTransformer.java
  src/main/java/org/codehaus/mojo/license/header/transformer/PhpFileHeaderTransformer.java
  src/main/java/org/codehaus/mojo/license/header/transformer/PropertiesFileHeaderTransformer.java
  src/main/java/org/codehaus/mojo/license/header/transformer/RstFileHeaderTransformer.java
  src/main/java/org/codehaus/mojo/license/header/transformer/SqlFileHeaderTransformer.java
  src/main/java/org/codehaus/mojo/license/header/transformer/XmlFileHeaderTransformer.java
Labels: enhancement

#502 Fix formatting in example-thirdparty document
  src/site/apt/examples/example-thirdparty.apt.vm
Labels: maintenance

#503 Add LICENSE.txt file
  LICENSE.txt
Labels: maintenance

#506 Use JDK 1.8 in ITs - allow build on JDK 20
  src/it/ISSUE-135/pom.xml
  src/it/ISSUE-31/pom.xml
  src/it/MLICENSE-45/pom.xml
  src/it/override-copyright-format/pom.xml
  src/it/update-file-header-test-mojo/pom.xml
Labels: maintenance

#414 Fix #413 Use 'GAV' for result keys in LicensedArtifactResolver
  src/it/download-licenses-exclude-transitive-deps/invoker.properties
  src/it/download-licenses-exclude-transitive-deps/pom.xml
  src/it/download-licenses-exclude-transitive-deps/postbuild.groovy
  src/it/download-licenses-exclude-transitive-deps/src/main/java/org/codehaus/mojo/HelloWorld.java
  src/main/java/org/codehaus/mojo/license/download/LicensedArtifactResolver.java
Labels: bug

#507 Use project.version instead of pom.version in ITs
  src/it/ISSUE-361/pom.xml
  src/it/download-licenses-exclude-transitive-deps/pom.xml
Labels: maintenance

#373 Fix #358, #352 NPE on site generation caused by null returned by deprecated MavenProject.getDependencyArtifacts()
  src/it/ISSUE-358/child-1/pom.xml
  src/it/ISSUE-358/invoker.properties
  src/it/ISSUE-358/pom.xml
  src/main/java/org/codehaus/mojo/license/AbstractThirdPartyReportMojo.java
  src/main/java/org/codehaus/mojo/license/AddThirdPartyMojo.java
  src/main/java/org/codehaus/mojo/license/AggregateDownloadLicensesMojo.java
  src/main/java/org/codehaus/mojo/license/DownloadLicensesMojo.java
  src/main/java/org/codehaus/mojo/license/LicensesXmlInsertVersionsMojo.java
  src/main/java/org/codehaus/mojo/license/utils/MojoHelper.java
Labels: bug

#512 Fix #508 - Avoid NPE in AggregatorAddThirdPartyMojo
  src/it/ISSUE-508/invoker.properties
  src/it/ISSUE-508/module-a/pom.xml
  src/it/ISSUE-508/pom.xml
  src/it/ISSUE-508/postbuild.groovy
  src/it/ISSUE-508/prebuild.groovy
  src/main/java/org/codehaus/mojo/license/AddThirdPartyMojo.java
Labels: bug

#513 Cleanups in FileUtil - direct use methods from NIO
  src/main/java/org/codehaus/mojo/license/AbstractAddThirdPartyMojo.java
  src/main/java/org/codehaus/mojo/license/AbstractDownloadLicensesMojo.java
  src/main/java/org/codehaus/mojo/license/AbstractFileHeaderMojo.java
  src/main/java/org/codehaus/mojo/license/AddThirdPartyMojo.java
  src/main/java/org/codehaus/mojo/license/LicensesXmlInsertVersionsMojo.java
  src/main/java/org/codehaus/mojo/license/RemoveFileHeaderMojo.java
  src/main/java/org/codehaus/mojo/license/UpdateProjectLicenseMojo.java
  src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyTool.java
  src/main/java/org/codehaus/mojo/license/utils/FileUtil.java
  src/main/java/org/codehaus/mojo/license/utils/SortedProperties.java
  src/test/java/org/codehaus/mojo/license/download/LicenseSummaryTest.java
Labels: maintenance
