Repository mojohaus/license-maven-plugin, pull requests merged in 2023-10, with the labels that each got.

#518 #517: optionally support copyright values that only contain inception year rather than year range
  src/it/inception-year-only-copyright-format/README.md
  src/it/inception-year-only-copyright-format/invoker.properties
  src/it/inception-year-only-copyright-format/pom.xml
  src/it/inception-year-only-copyright-format/postbuild.groovy
  src/it/inception-year-only-copyright-format/src/main/original/java/org/example/test/SampleFile.java
  src/it/inception-year-only-copyright-format/src/main/original/java/org/example/test/package-info.java
  src/main/java/org/codehaus/mojo/license/AbstractLicenseNameMojo.java
Labels: enhancement

#520 #519 minor updates to reduce verbosity of standard execution
  src/main/java/org/codehaus/mojo/license/model/LicenseRepository.java
  src/main/java/org/codehaus/mojo/license/model/LicenseStore.java
Labels: enhancement

#523 Downgrade plexus-xml to version 3.0.0
  pom.xml
Labels: dependencies

#525 Build improvements - one profile for ITs
  pom.xml
  src/it/ISSUE-145/submodule1/pom.xml
  src/it/MLICENSE-4/invoker.properties
  src/it/add-third-party-no-encoding/invoker.properties
  src/it/download-licenses-proxy/invoker.properties
Labels: maintenance
