Repository mojohaus/license-maven-plugin, pull requests merged in 2023-06, with the labels that each got.

#484 Add release-drafter
  .github/workflows/release-drafter.yml
Labels: build

#486 Recognize classpath protocol as external
  src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyTool.java
  src/main/java/org/codehaus/mojo/license/utils/UrlRequester.java
  src/test/java/org/codehaus/mojo/license/utils/UrlRequesterTest.java
Labels: enhancement

#491 Use license plugin version from parent, update THIRD-PARTY.properties
  pom.xml
  src/license/THIRD-PARTY.properties
Labels: maintenance

#362 Update GPL licenses
  src/main/resources/META-INF/licenses/agpl_v3/license.txt
  src/main/resources/META-INF/licenses/gpl_v1/license.txt
  src/main/resources/META-INF/licenses/gpl_v2/license.txt
  src/main/resources/META-INF/licenses/gpl_v3/license.txt
  src/main/resources/META-INF/licenses/lgpl_v2_1/license.txt
  src/main/resources/META-INF/licenses/lgpl_v3/license.txt
Labels: enhancement

#380 Fix #379 allow users to customize the copyright string format
  src/it/override-copyright-format/README.md
  src/it/override-copyright-format/invoker.properties
  src/it/override-copyright-format/pom.xml
  src/it/override-copyright-format/postbuild.groovy
  src/it/override-copyright-format/src/main/original/java/org/example/test/SampleFile.java
  src/it/override-copyright-format/src/main/original/java/org/example/test/package-info.java
  src/main/java/org/codehaus/mojo/license/AbstractFileHeaderMojo.java
  src/main/java/org/codehaus/mojo/license/AbstractLicenseNameMojo.java
  src/main/java/org/codehaus/mojo/license/model/Copyright.java
Labels: enhancement

#374 Fix #351 License override does not work for third-party dependencies with multiple licenses
  src/it/ISSUE-351/child1-multi-license/pom.xml
  src/it/ISSUE-351/child2-overriding/pom.xml
  src/it/ISSUE-351/child2-overriding/src/license/override-THIRD-PARTY.properties
  src/it/ISSUE-351/invoker.properties
  src/it/ISSUE-351/pom.xml
  src/it/ISSUE-351/postbuild.groovy
  src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyTool.java
  src/main/java/org/codehaus/mojo/license/model/LicenseMap.java
Labels: bug

#499 Log message about skip due to packaging in info level
  src/main/java/org/codehaus/mojo/license/AbstractLicenseMojo.java
Labels: enhancement
