Repository mojohaus/license-maven-plugin, pull requests merged in 2024-09, with the labels that each got.

#581 Enhance exception handling for license execution when the URL tag of the license is empty.
  src/main/java/org/codehaus/mojo/license/AbstractDownloadLicensesMojo.java
Labels: enhancement

#587 Revert "Enhance exception handling for license execution when the URL tag of the license is empty."
  src/main/java/org/codehaus/mojo/license/AbstractDownloadLicensesMojo.java
Labels: reverted

#588 Enhance exception handling for license execution when the URL tag of the license is empty.
  src/main/java/org/codehaus/mojo/license/AbstractDownloadLicensesMojo.java
Labels: enhancement

#580 Added an option to control if output directory is added as resource directory
  pom.xml
  src/main/java/org/codehaus/mojo/license/AddThirdPartyMojo.java
Labels: enhancement

#561 Fix issue #560: fail to download license file because license name contains invalid characters
  src/main/java/org/codehaus/mojo/license/AbstractDownloadLicensesMojo.java
Labels: bug

#589 Re-enable checkstyle plugin
  pom.xml
  src/main/java/org/codehaus/mojo/license/extended/spreadsheet/CalcFileWriter.java
  src/main/java/org/codehaus/mojo/license/extended/spreadsheet/ExcelFileWriter.java
  src/test/java/org/codehaus/mojo/license/LicenseMojoUtilsTest.java
  src/test/java/org/codehaus/mojo/license/MockLogger.java
  src/test/java/org/codehaus/mojo/license/download/LicenseSummaryTest.java
  src/test/java/org/codehaus/mojo/license/header/transformer/AbstractFileHeaderTransformerTest.java
  src/test/java/org/codehaus/mojo/license/spdx/SpdxLicenseListTest.java
Labels: maintenance
