Repository mojohaus/license-maven-plugin, pull requests merged in 2024-11, with the labels that each got.

#602 Drop Maven wrapper from project
  .mvn/README.txt
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: maintenance

#603 Update Doxia to 2.x stack
  pom.xml
  src/it/aggregate-third-party-report/postbuild.groovy
  src/main/java/org/codehaus/mojo/license/AbstractDownloadLicensesMojo.java
  src/main/java/org/codehaus/mojo/license/AbstractLicenseReportRenderer.java
  src/main/java/org/codehaus/mojo/license/AbstractThirdPartyReport.java
  src/main/java/org/codehaus/mojo/license/AggregatorThirdPartyReport.java
  src/main/java/org/codehaus/mojo/license/ThirdPartyReport.java
  src/main/java/org/codehaus/mojo/license/ThirdPartyReportRenderer.java
  src/main/java/org/codehaus/mojo/license/spdx/SpdxLicenseList.java
Labels: enhancement, dependencies

#605 Add Log4j2 to SLF4J Adapter
  pom.xml
Labels: maintenance

#607 licenseName is required
  src/main/java/org/codehaus/mojo/license/AbstractLicenseNameMojo.java
  src/main/java/org/codehaus/mojo/license/model/LicenseRepository.java
Labels: bug

#609 Manage open streams in correct way
  src/it/MLICENSE-44/pom.xml
  src/it/add-third-party-missing-file/pom.xml
  src/main/java/org/codehaus/mojo/license/AbstractFileHeaderMojo.java
  src/main/java/org/codehaus/mojo/license/RemoveFileHeaderMojo.java
  src/main/java/org/codehaus/mojo/license/model/License.java
  src/main/java/org/codehaus/mojo/license/model/LicenseRepository.java
  src/main/java/org/codehaus/mojo/license/model/LicenseStore.java
  src/main/java/org/codehaus/mojo/license/utils/FileUtil.java
  src/main/java/org/codehaus/mojo/license/utils/MojoHelper.java
  src/main/java/org/codehaus/mojo/license/utils/UrlRequester.java
Labels: bug

#610 Use WireMock in integration test
  pom.xml
  src/build/scripts/LittleProxyStart.groovy
  src/it/download-licenses-proxy/invoker.properties
  src/it/download-licenses-proxy/postbuild.groovy
  src/it/download-licenses-proxy/prebuild.groovy
Labels: maintenance

#613 Replace deprecated Component annotation
  src/main/java/org/codehaus/mojo/license/AbstractAddThirdPartyMojo.java
  src/main/java/org/codehaus/mojo/license/AbstractDownloadLicensesMojo.java
  src/main/java/org/codehaus/mojo/license/AbstractFileHeaderMojo.java
  src/main/java/org/codehaus/mojo/license/AbstractLicenseMojo.java
  src/main/java/org/codehaus/mojo/license/AbstractLicensesXmlMojo.java
  src/main/java/org/codehaus/mojo/license/AbstractThirdPartyReport.java
  src/main/java/org/codehaus/mojo/license/AddThirdPartyMojo.java
  src/main/java/org/codehaus/mojo/license/AggregateDownloadLicensesMojo.java
  src/main/java/org/codehaus/mojo/license/AggregatorAddThirdPartyMojo.java
  src/main/java/org/codehaus/mojo/license/AggregatorThirdPartyReport.java
  src/main/java/org/codehaus/mojo/license/CheckFileHeaderMojo.java
  src/main/java/org/codehaus/mojo/license/CommentStyleListMojo.java
  src/main/java/org/codehaus/mojo/license/DownloadLicensesMojo.java
  src/main/java/org/codehaus/mojo/license/LicensesXmlInsertVersionsMojo.java
  src/main/java/org/codehaus/mojo/license/RemoveFileHeaderMojo.java
  src/main/java/org/codehaus/mojo/license/ThirdPartyReport.java
  src/main/java/org/codehaus/mojo/license/UpdateFileHeaderMojo.java
  src/main/java/org/codehaus/mojo/license/api/DefaultThirdPartyTool.java
  src/main/java/org/codehaus/mojo/license/api/ThirdPartyTool.java
Labels: maintenance
